[package]
name = "qhtlcli"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "CLI utilities for QhtLink Firewall (Rust port WIP)"

[dependencies]
anyhow = "1"
qhtlcore = { path = "../qhtlcore" }
